import type { HttpMethod } from "../services/meta-client.js";
import type { InstagramApiMode } from "../services/acellere-meta-client.js";

export type CapabilityStatus =
  | "COVERED"
  | "COVERED_BY_ABSTRACTION"
  | "FACEBOOK_LOGIN_ONLY"
  | "INSTAGRAM_LOGIN_ONLY"
  | "DEPRECATED"
  | "NOT_EXPOSED_BY_META";

export type CapabilityCategory =
  | "auth"
  | "profile"
  | "media"
  | "publishing"
  | "insights"
  | "comments"
  | "hashtags"
  | "mentions"
  | "collaboration"
  | "messaging"
  | "messenger_profile"
  | "welcome_flows"
  | "webhooks"
  | "commerce"
  | "partnership"
  | "discovery"
  | "oembed";

export type ReadWriteClassification =
  | "READ"
  | "WRITE"
  | "WRITE_IDEMPOTENT"
  | "DESTRUCTIVE";

export interface InstagramCapability {
  id: string;
  category: CapabilityCategory;
  name: string;
  description: string;
  endpoint: string;
  method: HttpMethod;
  facebookLogin: boolean;
  instagramLogin: boolean;
  permissions: string[];
  permissionsByMode?: {
    "facebook-login": string[];
    "instagram-login": string[];
  };
  readWrite: ReadWriteClassification;
  status: CapabilityStatus;
  mcpTool?: string;
  notes?: string;
  verifiedDate: string;
}

export const INSTAGRAM_CAPABILITIES: Record<string, InstagramCapability> = {
  // ─── AUTH & BOOTSTRAP ──────────────────────────────────────────
  "auth.tokenDebug": {
    id: "auth.tokenDebug",
    category: "auth",
    name: "Debug Access Token",
    description: "Inspect token scopes, expiration, and app associations via /debug_token",
    endpoint: "GET /debug_token",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: [],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "meta_debug_token",
    verifiedDate: "2026-08-26",
  },
  "auth.tokenExchange": {
    id: "auth.tokenExchange",
    category: "auth",
    name: "Exchange Short-Lived Token for Long-Lived Token",
    description: "Exchange short-lived token for long-lived 60-day token",
    endpoint: "GET /access_token (IG) or GET /oauth/access_token (FB)",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: [],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "meta_exchange_token",
    verifiedDate: "2026-08-26",
  },
  "auth.tokenRefresh": {
    id: "auth.tokenRefresh",
    category: "auth",
    name: "Refresh Long-Lived Token",
    description: "Refresh long-lived access token before expiration",
    endpoint: "GET /refresh_access_token",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: [],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "meta_refresh_token",
    verifiedDate: "2026-08-26",
  },
  "auth.pageDiscovery": {
    id: "auth.pageDiscovery",
    category: "auth",
    name: "Facebook Page and IG Account Discovery",
    description: "Discover Facebook Pages and attached Instagram Professional Accounts",
    endpoint: "GET /me/accounts?fields=instagram_business_account{id,username,name}",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["pages_show_list", "pages_read_engagement", "instagram_basic"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_get_connection_info",
    notes: "Requires Facebook Login; not available via Instagram Login direct OAuth",
    verifiedDate: "2026-08-26",
  },
  "auth.capabilities": {
    id: "auth.capabilities",
    category: "auth",
    name: "Query Capabilities and Environment Matrix",
    description: "Returns active login mode, API version, and supported feature matrix",
    endpoint: "Internal MCP Capability Engine",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: [],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_capabilities",
    verifiedDate: "2026-08-26",
  },

  // ─── PROFILE ───────────────────────────────────────────────────
  "profile.get": {
    id: "profile.get",
    category: "profile",
    name: "Get Own Instagram Profile",
    description: "Get profile fields (id, username, name, biography, website, profile_picture_url, counts)",
    endpoint: "GET /{ig-user-id}",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_profile",
    verifiedDate: "2026-08-26",
  },

  // ─── MEDIA ─────────────────────────────────────────────────────
  "media.list": {
    id: "media.list",
    category: "media",
    name: "List Published Media",
    description: "List published posts, reels, and carousels for the account",
    endpoint: "GET /{ig-user-id}/media",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_media_list",
    verifiedDate: "2026-08-26",
  },
  "media.get": {
    id: "media.get",
    category: "media",
    name: "Get Media Details",
    description: "Get single media object details",
    endpoint: "GET /{ig-media-id}",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_media",
    verifiedDate: "2026-08-26",
  },
  "media.children": {
    id: "media.children",
    category: "media",
    name: "Get Carousel Media Children",
    description: "Get child items and media details of an album/carousel post",
    endpoint: "GET /{ig-media-id}/children",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_media_children",
    verifiedDate: "2026-08-26",
  },
  "media.stories": {
    id: "media.stories",
    category: "media",
    name: "Get Active Stories",
    description: "List currently active Stories published in the last 24 hours",
    endpoint: "GET /{ig-user-id}/stories",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_basic", "instagram_manage_insights"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_stories",
    verifiedDate: "2026-08-26",
  },
  "media.live": {
    id: "media.live",
    category: "media",
    name: "Get Active Live Broadcast Media",
    description: "List active live video broadcasts for the account",
    endpoint: "GET /{ig-user-id}/live_media",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_live_media",
    verifiedDate: "2026-08-26",
  },
  "media.delete": {
    id: "media.delete",
    category: "media",
    name: "Delete Media Post",
    description: "Delete an Instagram media post",
    endpoint: "DELETE /{ig-media-id}",
    method: "DELETE",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_content_publish"],
    readWrite: "DESTRUCTIVE",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_delete_media",
    notes: "Meta requires Facebook Login for media deletion; not available in Instagram Login",
    verifiedDate: "2026-08-26",
  },
  "media.toggleComments": {
    id: "media.toggleComments",
    category: "media",
    name: "Enable or Disable Comments on Media Post",
    description: "Turn comment thread on/off on a published post",
    endpoint: "POST /{ig-media-id}?comment_enabled=true|false",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_comments"],
    readWrite: "WRITE_IDEMPOTENT",
    status: "COVERED",
    mcpTool: "ig_toggle_comments",
    verifiedDate: "2026-08-26",
  },

  // ─── PUBLISHING ────────────────────────────────────────────────
  "publishing.photo": {
    id: "publishing.photo",
    category: "publishing",
    name: "Publish Single Photo Post",
    description: "Create container and publish single image feed post",
    endpoint: "POST /{ig-user-id}/media + POST /{ig-user-id}/media_publish",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_content_publish"],
    readWrite: "WRITE",
    status: "COVERED",
    mcpTool: "ig_publish_photo",
    verifiedDate: "2026-08-26",
  },
  "publishing.reel": {
    id: "publishing.reel",
    category: "publishing",
    name: "Publish Reel Video Post",
    description: "Create video container and publish Instagram Reel",
    endpoint: "POST /{ig-user-id}/media + POST /{ig-user-id}/media_publish",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_content_publish"],
    readWrite: "WRITE",
    status: "COVERED",
    mcpTool: "ig_publish_reel",
    verifiedDate: "2026-08-26",
  },
  "publishing.carousel": {
    id: "publishing.carousel",
    category: "publishing",
    name: "Publish Carousel Album Post",
    description: "Create item containers, parent carousel container, and publish album",
    endpoint: "POST /{ig-user-id}/media + POST /{ig-user-id}/media_publish",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_content_publish"],
    readWrite: "WRITE",
    status: "COVERED",
    mcpTool: "ig_publish_carousel",
    verifiedDate: "2026-08-26",
  },
  "publishing.story": {
    id: "publishing.story",
    category: "publishing",
    name: "Publish Story Post",
    description: "Create story container and publish 24-hour Story",
    endpoint: "POST /{ig-user-id}/media (media_type=STORIES) + POST /{ig-user-id}/media_publish",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_content_publish"],
    readWrite: "WRITE",
    status: "COVERED",
    mcpTool: "ig_publish_story",
    verifiedDate: "2026-08-26",
  },
  "publishing.containerStatus": {
    id: "publishing.containerStatus",
    category: "publishing",
    name: "Check Media Container Processing Status",
    description: "Query container status_code (FINISHED, IN_PROGRESS, ERROR)",
    endpoint: "GET /{creation-id}?fields=status_code,status",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_content_publish"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_container_status",
    verifiedDate: "2026-08-26",
  },
  "publishing.limit": {
    id: "publishing.limit",
    category: "publishing",
    name: "Check Content Publishing Limit Quota",
    description: "Query remaining publishing quota and quota duration",
    endpoint: "GET /{ig-user-id}/content_publishing_limit",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_content_publish"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_content_publishing_limit",
    verifiedDate: "2026-08-26",
  },

  // ─── INSIGHTS ──────────────────────────────────────────────────
  "insights.account": {
    id: "insights.account",
    category: "insights",
    name: "Account-Level Insights",
    description: "Query views, reach, total interactions, follower demographics",
    endpoint: "GET /{ig-user-id}/insights",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_insights"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_account_insights",
    verifiedDate: "2026-08-26",
  },
  "insights.media": {
    id: "insights.media",
    category: "insights",
    name: "Media-Level Insights",
    description: "Query views, reach, likes, comments, shares, saved per post",
    endpoint: "GET /{ig-media-id}/insights",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_insights"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_media_insights",
    verifiedDate: "2026-08-26",
  },

  // ─── COMMENTS ──────────────────────────────────────────────────
  "comments.list": {
    id: "comments.list",
    category: "comments",
    name: "List Comments on Post",
    description: "Get top-level comments on a post",
    endpoint: "GET /{ig-media-id}/comments",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_comments"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_comments",
    verifiedDate: "2026-08-26",
  },
  "comments.get": {
    id: "comments.get",
    category: "comments",
    name: "Get Comment Details",
    description: "Get single comment object details",
    endpoint: "GET /{ig-comment-id}",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_comments"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_comment",
    verifiedDate: "2026-08-26",
  },
  "comments.create": {
    id: "comments.create",
    category: "comments",
    name: "Post Top-Level Comment",
    description: "Publish a comment on a media post",
    endpoint: "POST /{ig-media-id}/comments",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_comments"],
    readWrite: "WRITE",
    status: "COVERED",
    mcpTool: "ig_post_comment",
    verifiedDate: "2026-08-26",
  },
  "comments.replies": {
    id: "comments.replies",
    category: "comments",
    name: "List Replies to Comment",
    description: "Get threaded replies to a parent comment",
    endpoint: "GET /{ig-comment-id}/replies",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_comments"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_replies",
    verifiedDate: "2026-08-26",
  },
  "comments.reply": {
    id: "comments.reply",
    category: "comments",
    name: "Reply to a Comment",
    description: "Post a reply to an existing comment",
    endpoint: "POST /{ig-comment-id}/replies",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_comments"],
    readWrite: "WRITE",
    status: "COVERED",
    mcpTool: "ig_reply_to_comment",
    verifiedDate: "2026-08-26",
  },
  "comments.hide": {
    id: "comments.hide",
    category: "comments",
    name: "Hide or Unhide Comment",
    description: "Set hide=true|false on a comment",
    endpoint: "POST /{ig-comment-id}?hide=true|false",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_comments"],
    readWrite: "WRITE_IDEMPOTENT",
    status: "COVERED",
    mcpTool: "ig_hide_comment",
    verifiedDate: "2026-08-26",
  },
  "comments.delete": {
    id: "comments.delete",
    category: "comments",
    name: "Delete Comment",
    description: "Delete an Instagram comment",
    endpoint: "DELETE /{ig-comment-id}",
    method: "DELETE",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_comments"],
    readWrite: "DESTRUCTIVE",
    status: "COVERED",
    mcpTool: "ig_delete_comment",
    verifiedDate: "2026-08-26",
  },
  "comments.privateReply": {
    id: "comments.privateReply",
    category: "comments",
    name: "Send Private Reply to Comment",
    description: "Send a direct message reply to a comment within 7 days",
    endpoint: "POST /{ig-user-id}/messages (recipient={comment_id})",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages", "instagram_manage_comments"],
    readWrite: "WRITE",
    status: "COVERED",
    mcpTool: "ig_send_private_reply",
    verifiedDate: "2026-08-26",
  },

  // ─── HASHTAGS ──────────────────────────────────────────────────
  "hashtags.search": {
    id: "hashtags.search",
    category: "hashtags",
    name: "Search Hashtag ID by Name",
    description: "Lookup Instagram Hashtag ID for a given query",
    endpoint: "GET /ig_hashtag_search?user_id={ig-user-id}&q={hashtag_name}",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_search_hashtag",
    notes: "Meta requires Facebook Login for Hashtag Search; not available in Instagram Login",
    verifiedDate: "2026-08-26",
  },
  "hashtags.get": {
    id: "hashtags.get",
    category: "hashtags",
    name: "Get Hashtag Info",
    description: "Get metadata for a hashtag ID",
    endpoint: "GET /{hashtag-id}",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_get_hashtag",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "hashtags.recentMedia": {
    id: "hashtags.recentMedia",
    category: "hashtags",
    name: "Get Recent Media for Hashtag",
    description: "Get recent public posts tagged with the hashtag (subject to 30 unique hashtags / 7 days quota)",
    endpoint: "GET /{hashtag-id}/recent_media?user_id={ig-user-id}",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_get_hashtag_recent",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "hashtags.topMedia": {
    id: "hashtags.topMedia",
    category: "hashtags",
    name: "Get Top Media for Hashtag",
    description: "Get top public posts tagged with the hashtag",
    endpoint: "GET /{hashtag-id}/top_media?user_id={ig-user-id}",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_get_hashtag_top",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "hashtags.recentlySearched": {
    id: "hashtags.recentlySearched",
    category: "hashtags",
    name: "Get Recently Searched Hashtags Quota",
    description: "List hashtags queried in the current 7-day rolling window to monitor quota usage",
    endpoint: "GET /{ig-user-id}/recently_searched_hashtags",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_get_recently_searched_hashtags",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },

  // ─── MENTIONS & TAGS ───────────────────────────────────────────
  "mentions.taggedMedia": {
    id: "mentions.taggedMedia",
    category: "mentions",
    name: "Get Tagged Media",
    description: "List public media posts in which the account is tagged",
    endpoint: "GET /{ig-user-id}/tags",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_basic", "instagram_manage_comments"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_tagged_media",
    verifiedDate: "2026-08-26",
  },
  "mentions.mentionedComment": {
    id: "mentions.mentionedComment",
    category: "mentions",
    name: "Get Mentioned Comment Details",
    description: "Lookup comment details from a mention webhook",
    endpoint: "GET /{ig-user-id}?fields=mentioned_comment.comment_id({comment_id}){...}",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_basic", "instagram_manage_comments"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_mentioned_comment",
    verifiedDate: "2026-08-26",
  },
  "mentions.mentionedMedia": {
    id: "mentions.mentionedMedia",
    category: "mentions",
    name: "Get Mentioned Media Details",
    description: "Lookup caption and media details from a caption mention webhook",
    endpoint: "GET /{ig-user-id}?fields=mentioned_media.media_id({media_id}){...}",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_basic", "instagram_manage_comments"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_mentioned_media",
    verifiedDate: "2026-08-26",
  },
  "mentions.reply": {
    id: "mentions.reply",
    category: "mentions",
    name: "Reply to Mentioned Media or Comment",
    description: "Publish a reply comment to a post/comment mentioning the account",
    endpoint: "POST /{ig-user-id}/mentions",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_comments"],
    readWrite: "WRITE",
    status: "COVERED",
    mcpTool: "ig_reply_to_mention",
    verifiedDate: "2026-08-26",
  },

  // ─── COLLABORATION ─────────────────────────────────────────────
  "collaboration.invites": {
    id: "collaboration.invites",
    category: "collaboration",
    name: "Get Pending Collaboration Invites",
    description: "List pending co-author collaboration invites received by the account",
    endpoint: "GET /{ig-user-id}/collaboration_invites",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_basic", "instagram_content_publish"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_collaboration_invites",
    verifiedDate: "2026-08-26",
  },
  "collaboration.respond": {
    id: "collaboration.respond",
    category: "collaboration",
    name: "Accept or Decline Collaboration Invite",
    description: "Accept or decline a co-author invite for a media post",
    endpoint: "POST /{ig-user-id}/collaboration_invites?media_id=...&action=ACCEPT|DECLINE",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_content_publish"],
    readWrite: "WRITE_IDEMPOTENT",
    status: "COVERED",
    mcpTool: "ig_respond_collaboration_invite",
    verifiedDate: "2026-08-26",
  },
  "collaboration.posts": {
    id: "collaboration.posts",
    category: "collaboration",
    name: "Get Collaborative Media Posts",
    description: "List published collaborative posts where this account is a accepted collaborator",
    endpoint: "GET /{ig-user-id}/collaborative_posts",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_collaborative_posts",
    verifiedDate: "2026-08-26",
  },

  // ─── MESSAGING & SEND API ──────────────────────────────────────
  "messaging.conversations": {
    id: "messaging.conversations",
    category: "messaging",
    name: "List DM Conversations",
    description: "List Instagram Direct conversations, folders, unread counts, and participants",
    endpoint: "GET /{target-id}/conversations?platform=instagram",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_conversations",
    verifiedDate: "2026-08-26",
  },
  "messaging.messages": {
    id: "messaging.messages",
    category: "messaging",
    name: "List Messages in Conversation",
    description: "Get message history for a conversation ID",
    endpoint: "GET /{conversation-id}/messages",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_messages",
    verifiedDate: "2026-08-26",
  },
  "messaging.messageDetail": {
    id: "messaging.messageDetail",
    category: "messaging",
    name: "Get Message Details",
    description: "Get message object, attachments, shares, reactions",
    endpoint: "GET /{message-id}",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_message",
    verifiedDate: "2026-08-26",
  },
  "messaging.sendText": {
    id: "messaging.sendText",
    category: "messaging",
    name: "Send Text Message",
    description: "Send Direct Message text with messaging_type or HUMAN_AGENT tag",
    endpoint: "POST /{ig-user-id}/messages",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "WRITE",
    status: "COVERED",
    mcpTool: "ig_send_message",
    verifiedDate: "2026-08-26",
  },
  "messaging.sendMedia": {
    id: "messaging.sendMedia",
    category: "messaging",
    name: "Send Media Message",
    description: "Send Image, Video, Audio, or GIF DM via URL or attachment_id",
    endpoint: "POST /{ig-user-id}/messages (attachment payload)",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "WRITE",
    status: "COVERED",
    mcpTool: "ig_send_media_message",
    verifiedDate: "2026-08-26",
  },
  "messaging.sendQuickReplies": {
    id: "messaging.sendQuickReplies",
    category: "messaging",
    name: "Send Quick Replies Message",
    description: "Send text message with up to 13 quick reply buttons",
    endpoint: "POST /{ig-user-id}/messages (quick_replies payload)",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "WRITE",
    status: "COVERED",
    mcpTool: "ig_send_quick_replies",
    verifiedDate: "2026-08-26",
  },
  "messaging.sendGenericTemplate": {
    id: "messaging.sendGenericTemplate",
    category: "messaging",
    name: "Send Generic Template Carousel Message",
    description: "Send interactive generic template card/carousel with buttons and URLs",
    endpoint: "POST /{ig-user-id}/messages (template generic payload)",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "WRITE",
    status: "COVERED",
    mcpTool: "ig_send_generic_template",
    verifiedDate: "2026-08-26",
  },
  "messaging.sendButtonTemplate": {
    id: "messaging.sendButtonTemplate",
    category: "messaging",
    name: "Send Button Template Message",
    description: "Send text prompt with call-to-action buttons",
    endpoint: "POST /{ig-user-id}/messages (template button payload)",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "WRITE",
    status: "COVERED",
    mcpTool: "ig_send_button_template",
    verifiedDate: "2026-08-26",
  },
  "messaging.reaction": {
    id: "messaging.reaction",
    category: "messaging",
    name: "React to a Direct Message",
    description: "Add an emoji reaction to a message",
    endpoint: "POST /{ig-user-id}/messages (sender_action=react)",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "WRITE_IDEMPOTENT",
    status: "COVERED",
    mcpTool: "ig_send_reaction",
    verifiedDate: "2026-08-26",
  },
  "messaging.removeReaction": {
    id: "messaging.removeReaction",
    category: "messaging",
    name: "Remove Reaction from Direct Message",
    description: "Remove an emoji reaction from a message",
    endpoint: "POST /{ig-user-id}/messages (sender_action=unreact)",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "WRITE_IDEMPOTENT",
    status: "COVERED",
    mcpTool: "ig_delete_reaction",
    verifiedDate: "2026-08-26",
  },
  "messaging.senderAction": {
    id: "messaging.senderAction",
    category: "messaging",
    name: "Send Typing Indicator or Mark Seen",
    description: "Set typing_on, typing_off, or mark_seen in a conversation",
    endpoint: "POST /{ig-user-id}/messages (sender_action)",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "WRITE_IDEMPOTENT",
    status: "COVERED",
    mcpTool: "ig_send_sender_action",
    verifiedDate: "2026-08-26",
  },
  "messaging.userProfileByIgsid": {
    id: "messaging.userProfileByIgsid",
    category: "messaging",
    name: "Get User Profile by IGSID",
    description: "Get name, profile pic, and follower count for an Instagram-Scoped ID (IGSID)",
    endpoint: "GET /{igsid}?fields=name,profile_pic,follower_count,is_user_follow_business,is_business_follow_user",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_user_profile_by_igsid",
    verifiedDate: "2026-08-26",
  },
  "messaging.uploadAttachment": {
    id: "messaging.uploadAttachment",
    category: "messaging",
    name: "Upload Reusable Message Attachment",
    description: "Upload an image, video, audio, or file to obtain reusable attachment_id",
    endpoint: "POST /{ig-user-id}/message_attachments",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "WRITE",
    status: "COVERED",
    mcpTool: "ig_upload_attachment",
    verifiedDate: "2026-08-26",
  },

  // ─── MESSENGER PROFILE & AUTOMATION ────────────────────────────
  "messengerProfile.get": {
    id: "messengerProfile.get",
    category: "messenger_profile",
    name: "Get Messenger Profile Settings",
    description: "Get ice_breakers, persistent_menu, greeting settings for Direct",
    endpoint: "GET /{ig-user-id}/messenger_profile?fields=ice_breakers,persistent_menu,greeting,commands",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_messenger_profile",
    verifiedDate: "2026-08-26",
  },
  "messengerProfile.setIceBreakers": {
    id: "messengerProfile.setIceBreakers",
    category: "messenger_profile",
    name: "Set Ice Breakers for Instagram Direct",
    description: "Configure FAQs / Ice Breaker question buttons shown to new users",
    endpoint: "POST /{ig-user-id}/messenger_profile (ice_breakers payload)",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "WRITE_IDEMPOTENT",
    status: "COVERED",
    mcpTool: "ig_set_ice_breakers",
    verifiedDate: "2026-08-26",
  },
  "messengerProfile.deleteIceBreakers": {
    id: "messengerProfile.deleteIceBreakers",
    category: "messenger_profile",
    name: "Delete Ice Breakers",
    description: "Delete Ice Breakers configuration for the account",
    endpoint: "DELETE /{ig-user-id}/messenger_profile (fields=['ice_breakers'])",
    method: "DELETE",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "DESTRUCTIVE",
    status: "COVERED",
    mcpTool: "ig_delete_ice_breakers",
    verifiedDate: "2026-08-26",
  },
  "messengerProfile.setPersistentMenu": {
    id: "messengerProfile.setPersistentMenu",
    category: "messenger_profile",
    name: "Set Persistent Menu for Instagram Direct",
    description: "Configure persistent menu call-to-actions in Direct composer",
    endpoint: "POST /{ig-user-id}/messenger_profile (persistent_menu payload)",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "WRITE_IDEMPOTENT",
    status: "COVERED",
    mcpTool: "ig_set_persistent_menu",
    verifiedDate: "2026-08-26",
  },
  "messengerProfile.deletePersistentMenu": {
    id: "messengerProfile.deletePersistentMenu",
    category: "messenger_profile",
    name: "Delete Persistent Menu",
    description: "Delete persistent menu configuration for the account",
    endpoint: "DELETE /{ig-user-id}/messenger_profile (fields=['persistent_menu'])",
    method: "DELETE",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "DESTRUCTIVE",
    status: "COVERED",
    mcpTool: "ig_delete_persistent_menu",
    verifiedDate: "2026-08-26",
  },

  // ─── WELCOME MESSAGE FLOWS ─────────────────────────────────────
  "welcomeFlows.list": {
    id: "welcomeFlows.list",
    category: "welcome_flows",
    name: "List Welcome Message Flows",
    description: "List welcome message automation flows",
    endpoint: "GET /{ig-user-id}/welcome_message_flows",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_list_welcome_message_flows",
    verifiedDate: "2026-08-26",
  },
  "welcomeFlows.get": {
    id: "welcomeFlows.get",
    category: "welcome_flows",
    name: "Get Welcome Message Flow Details",
    description: "Get single welcome message flow metadata",
    endpoint: "GET /{welcome-message-flow-id}",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_welcome_message_flow",
    verifiedDate: "2026-08-26",
  },
  "welcomeFlows.set": {
    id: "welcomeFlows.set",
    category: "welcome_flows",
    name: "Create or Set Welcome Message Flow",
    description: "Create or configure a welcome message flow",
    endpoint: "POST /{ig-user-id}/welcome_message_flows",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "WRITE",
    status: "COVERED",
    mcpTool: "ig_set_welcome_message_flow",
    verifiedDate: "2026-08-26",
  },
  "welcomeFlows.delete": {
    id: "welcomeFlows.delete",
    category: "welcome_flows",
    name: "Delete Welcome Message Flow",
    description: "Delete an existing welcome message flow",
    endpoint: "DELETE /{welcome-message-flow-id}",
    method: "DELETE",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages"],
    readWrite: "DESTRUCTIVE",
    status: "COVERED",
    mcpTool: "ig_delete_welcome_message_flow",
    verifiedDate: "2026-08-26",
  },

  // ─── WEBHOOKS ──────────────────────────────────────────────────
  "webhooks.appSubscriptions": {
    id: "webhooks.appSubscriptions",
    category: "webhooks",
    name: "Meta App Webhook Subscriptions",
    description: "List or configure Meta App level webhook subscriptions for Instagram",
    endpoint: "GET / POST / DELETE /{app-id}/subscriptions",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: [],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "meta_get_webhook_subscriptions",
    verifiedDate: "2026-08-26",
  },
  "webhooks.subscribedApps": {
    id: "webhooks.subscribedApps",
    category: "webhooks",
    name: "Get Subscribed Apps on Instagram Account",
    description: "List Meta Apps subscribed to webhooks on this Instagram account",
    endpoint: "GET /{ig-user-id}/subscribed_apps",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages", "instagram_manage_comments"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_subscribed_apps",
    verifiedDate: "2026-08-26",
  },
  "webhooks.subscribeApp": {
    id: "webhooks.subscribeApp",
    category: "webhooks",
    name: "Subscribe App to Instagram Account Webhooks",
    description: "Subscribe App to receive real-time webhook events (messages, comments, mentions)",
    endpoint: "POST /{ig-user-id}/subscribed_apps?subscribed_fields=...",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages", "instagram_manage_comments"],
    readWrite: "WRITE_IDEMPOTENT",
    status: "COVERED",
    mcpTool: "ig_subscribe_app",
    verifiedDate: "2026-08-26",
  },
  "webhooks.unsubscribeApp": {
    id: "webhooks.unsubscribeApp",
    category: "webhooks",
    name: "Unsubscribe App from Instagram Account Webhooks",
    description: "Remove webhook subscription from this Instagram account",
    endpoint: "DELETE /{ig-user-id}/subscribed_apps",
    method: "DELETE",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["instagram_manage_messages", "instagram_manage_comments"],
    readWrite: "DESTRUCTIVE",
    status: "COVERED",
    mcpTool: "ig_unsubscribe_app",
    verifiedDate: "2026-08-26",
  },
  "webhooks.receiver": {
    id: "webhooks.receiver",
    category: "webhooks",
    name: "Cloudflare Worker Webhook Receiver and Event Normalizer",
    description: "HTTP endpoint /webhooks/instagram for verification challenge and signed event processing",
    endpoint: "GET / POST /webhooks/instagram",
    method: "POST",
    facebookLogin: true,
    instagramLogin: true,
    permissions: [],
    readWrite: "READ",
    status: "COVERED_BY_ABSTRACTION",
    notes: "Receiver hosted at /webhooks/instagram with HMAC SHA-256 validation and normalized event dispatcher",
    verifiedDate: "2026-08-26",
  },

  // ─── COMMERCE & PRODUCT TAGGING ────────────────────────────────
  "commerce.catalogs": {
    id: "commerce.catalogs",
    category: "commerce",
    name: "Get Available Product Catalogs",
    description: "List commerce product catalogs connected to the Instagram account",
    endpoint: "GET /{ig-user-id}/available_catalogs",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_shopping_tag_products", "catalog_management"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_get_available_catalogs",
    notes: "Meta requires Facebook Login; Product Tagging is not supported via Instagram Login",
    verifiedDate: "2026-08-26",
  },
  "commerce.catalogProducts": {
    id: "commerce.catalogProducts",
    category: "commerce",
    name: "Search Products in Catalog",
    description: "Search products and variants in an attached commerce catalog",
    endpoint: "GET /{catalog-id}/products?fields=id,name,retailer_id,price,image_url,availability",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_shopping_tag_products", "catalog_management"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_get_catalog_products",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "commerce.productTags": {
    id: "commerce.productTags",
    category: "commerce",
    name: "Get Product Tags on Media",
    description: "Get product tags attached to a published post",
    endpoint: "GET /{ig-media-id}/product_tags",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_shopping_tag_products"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_get_product_tags",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "commerce.createProductTags": {
    id: "commerce.createProductTags",
    category: "commerce",
    name: "Create or Update Product Tags on Media",
    description: "Tag catalog products on an eligible media post",
    endpoint: "POST /{ig-media-id}/product_tags (updated_tags payload)",
    method: "POST",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_shopping_tag_products"],
    readWrite: "WRITE",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_create_product_tags",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "commerce.deleteProductTags": {
    id: "commerce.deleteProductTags",
    category: "commerce",
    name: "Delete Product Tag from Media",
    description: "Remove a product tag from a published post",
    endpoint: "DELETE /{ig-media-id}/product_tags?deleted_tags=...",
    method: "DELETE",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_shopping_tag_products"],
    readWrite: "DESTRUCTIVE",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_delete_product_tags",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "commerce.productAppeal": {
    id: "commerce.productAppeal",
    category: "commerce",
    name: "Get Product Appeal Status",
    description: "Check status of rejected product tag appeal",
    endpoint: "GET /{product-id}/product_appeal",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_shopping_tag_products"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_get_product_appeal",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "commerce.submitProductAppeal": {
    id: "commerce.submitProductAppeal",
    category: "commerce",
    name: "Submit Product Tag Appeal",
    description: "Submit appeal for a rejected product tag",
    endpoint: "POST /{product-id}/product_appeal",
    method: "POST",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_shopping_tag_products"],
    readWrite: "WRITE",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_submit_product_appeal",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },

  // ─── BRANDED CONTENT & PARTNERSHIP ADS ─────────────────────────
  "partnership.adPermissions": {
    id: "partnership.adPermissions",
    category: "partnership",
    name: "Get Branded Content Ad Permissions",
    description: "Query creator ad permissions granted to partner brands",
    endpoint: "GET /{ig-user-id}/branded_content_ad_permissions",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic", "ads_read"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_get_branded_content_ad_permissions",
    notes: "Meta requires Facebook Login; Ads are not exposed via Instagram Login",
    verifiedDate: "2026-08-26",
  },
  "partnership.advertisableMedia": {
    id: "partnership.advertisableMedia",
    category: "partnership",
    name: "Get Branded Content Advertisable Media",
    description: "List media posts eligible to be boosted or converted into Partnership Ads",
    endpoint: "GET /{ig-user-id}/branded_content_advertisable_medias",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic", "ads_read"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_get_advertisable_media",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "partnership.authorizedAdAccounts": {
    id: "partnership.authorizedAdAccounts",
    category: "partnership",
    name: "Get Authorized Ad Accounts for Branded Content",
    description: "List Ad Account IDs permitted to promote this creator's posts",
    endpoint: "GET /{ig-user-id}/authorized_ad_accounts",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic", "ads_read"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_get_authorized_ad_accounts",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "partnership.setAuthorizedAdAccount": {
    id: "partnership.setAuthorizedAdAccount",
    category: "partnership",
    name: "Authorize Ad Account for Creator Promotion",
    description: "Grant Partnership Ad creation permission to a partner Ad Account ID",
    endpoint: "POST /{ig-user-id}/authorized_ad_accounts?ad_account_id=...",
    method: "POST",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic", "ads_management"],
    readWrite: "WRITE_IDEMPOTENT",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_set_authorized_ad_account",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "partnership.deleteAuthorizedAdAccount": {
    id: "partnership.deleteAuthorizedAdAccount",
    category: "partnership",
    name: "Revoke Ad Account Authorization",
    description: "Revoke Partnership Ad creation permission from an Ad Account ID",
    endpoint: "DELETE /{ig-user-id}/authorized_ad_accounts?ad_account_id=...",
    method: "DELETE",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic", "ads_management"],
    readWrite: "DESTRUCTIVE",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_delete_authorized_ad_account",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "partnership.tagApprovalRequests": {
    id: "partnership.tagApprovalRequests",
    category: "partnership",
    name: "Get Branded Content Tag Approval Requests",
    description: "List pending partner brand tag approval requests",
    endpoint: "GET /{ig-user-id}/tag_approval_requests",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic", "instagram_branded_content_brand"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_get_tag_approval_requests",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "partnership.updateTagApproval": {
    id: "partnership.updateTagApproval",
    category: "partnership",
    name: "Approve or Reject Branded Content Tag Request",
    description: "Approve or reject a brand partner's request to tag the creator",
    endpoint: "POST /{ig-user-id}/tag_approval_requests?user_id=...&action=APPROVE|REJECT",
    method: "POST",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic", "instagram_branded_content_brand"],
    readWrite: "WRITE_IDEMPOTENT",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_update_tag_approval",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },

  // ─── BUSINESS DISCOVERY ────────────────────────────────────────
  "discovery.profile": {
    id: "discovery.profile",
    category: "discovery",
    name: "Instagram Business Discovery Profile",
    description: "Lookup another public Business/Creator account's profile with 10 fields",
    endpoint: "GET /{ig-user-id}?fields=business_discovery.username({username}){...}",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_business_discovery",
    notes: "Meta requires Facebook Login; not available via Instagram Login",
    verifiedDate: "2026-08-26",
  },
  "discovery.media": {
    id: "discovery.media",
    category: "discovery",
    name: "Instagram Business Discovery Media",
    description: "Collect recent public posts, carousels, and view counts of another account",
    endpoint: "GET /{ig-user-id}?fields=business_discovery.username({username}){media{...}}",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_get_business_media",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "discovery.analytics": {
    id: "discovery.analytics",
    category: "discovery",
    name: "Competitor Deterministic Analytics",
    description: "Compute deterministic metrics, public engagement rate, format breakdown",
    endpoint: "Aggregated via Business Discovery Media",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_analyze_business",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "discovery.comparison": {
    id: "discovery.comparison",
    category: "discovery",
    name: "Multi-Competitor Benchmark",
    description: "Side-by-side comparison of 1 to 10 competitors and metric leaders",
    endpoint: "Aggregated via Business Discovery Media",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_compare_businesses",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "discovery.tracking": {
    id: "discovery.tracking",
    category: "discovery",
    name: "Competitor Historical Snapshot Tracking",
    description: "Track competitor snapshots, daily collection, and growth delta over time",
    endpoint: "Internal Store + Business Discovery",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_get_business_history",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },
  "discovery.research": {
    id: "discovery.research",
    category: "discovery",
    name: "Competitor Market Research Orchestrator",
    description: "Orchestrates full market research dataset for downstream LLMs",
    endpoint: "Aggregated via Business Discovery",
    method: "GET",
    facebookLogin: true,
    instagramLogin: false,
    permissions: ["instagram_basic"],
    readWrite: "READ",
    status: "FACEBOOK_LOGIN_ONLY",
    mcpTool: "ig_competitor_research",
    notes: "Meta requires Facebook Login",
    verifiedDate: "2026-08-26",
  },

  // ─── OEMBED ────────────────────────────────────────────────────
  "oembed.get": {
    id: "oembed.get",
    category: "oembed",
    name: "Instagram oEmbed",
    description: "Get HTML embed code and metadata for public Instagram post/reel URL",
    endpoint: "GET /instagram_oembed?url={permalink}",
    method: "GET",
    facebookLogin: true,
    instagramLogin: true,
    permissions: ["oEmbed Read App Feature"],
    readWrite: "READ",
    status: "COVERED",
    mcpTool: "ig_get_oembed",
    verifiedDate: "2026-08-26",
  },
};

export class InstagramCapabilityError extends Error {
  readonly capabilityId: string;
  readonly currentLoginMode: InstagramApiMode;
  readonly requiredLoginMode: "facebook-login" | "instagram-login";
  readonly requiredPermissions: string[];
  readonly remediation: string;

  constructor(capability: InstagramCapability, currentMode: InstagramApiMode) {
    const requiredMode = capability.facebookLogin ? "facebook-login" : "instagram-login";
    const perms = capability.permissions.join(", ") || "None";
    const message =
      `Capability "${capability.id}" (${capability.name}) is unavailable in current mode "${currentMode}". ` +
      `This endpoint requires INSTAGRAM_API_MODE="${requiredMode}" with permission(s): [${perms}]. ` +
      (capability.notes ? `Meta constraint: ${capability.notes}.` : "");

    super(message);
    this.name = "InstagramCapabilityError";
    this.capabilityId = capability.id;
    this.currentLoginMode = currentMode;
    this.requiredLoginMode = requiredMode;
    this.requiredPermissions = capability.permissions;
    this.remediation = `Switch server configuration to INSTAGRAM_API_MODE=${requiredMode} and verify that the token possesses required scopes: ${perms}.`;
  }
}

export function isCapabilitySupported(
  mode: InstagramApiMode,
  capabilityId: string
): boolean {
  const cap = INSTAGRAM_CAPABILITIES[capabilityId];
  if (!cap) return false;
  if (mode === "facebook-login") return cap.facebookLogin;
  if (mode === "instagram-login") return cap.instagramLogin;
  return false;
}

export function requireInstagramCapability(
  mode: InstagramApiMode,
  capabilityId: string
): InstagramCapability {
  const cap = INSTAGRAM_CAPABILITIES[capabilityId];
  if (!cap) {
    throw new Error(`Unknown Instagram capability: "${capabilityId}".`);
  }

  const supported =
    mode === "facebook-login" ? cap.facebookLogin : cap.instagramLogin;

  if (!supported) {
    throw new InstagramCapabilityError(cap, mode);
  }

  return cap;
}

export function getCapabilitiesSummary(mode: InstagramApiMode): {
  login_mode: InstagramApiMode;
  total_capabilities: number;
  available_capabilities_count: number;
  unavailable_capabilities_count: number;
  available_capabilities: InstagramCapability[];
  unavailable_capabilities: InstagramCapability[];
} {
  const all = Object.values(INSTAGRAM_CAPABILITIES);
  const available = all.filter((c) => (mode === "facebook-login" ? c.facebookLogin : c.instagramLogin));
  const unavailable = all.filter((c) => !(mode === "facebook-login" ? c.facebookLogin : c.instagramLogin));

  return {
    login_mode: mode,
    total_capabilities: all.length,
    available_capabilities_count: available.length,
    unavailable_capabilities_count: unavailable.length,
    available_capabilities: available,
    unavailable_capabilities: unavailable,
  };
}
