import { describe, it, expect, vi } from "vitest";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerAll } from "./register-all.js";
import type { MetaClient } from "./services/meta-client.js";

function makeMockServer() {
  const tools: string[] = [];
  const resources: { name: string; uri: string }[] = [];
  const prompts: string[] = [];
  return {
    tools,
    resources,
    prompts,
    registerTool: vi.fn((name: string) => tools.push(name)),
    registerResource: vi.fn((name: string, uri: string) => resources.push({ name, uri })),
    registerPrompt: vi.fn((name: string) => prompts.push(name)),
  };
}

describe("registerAll", () => {
  it("registers every tool, resource, and prompt in the expected order", () => {
    const server = makeMockServer();
    const client = {} as unknown as MetaClient;

    registerAll(server as unknown as McpServer, client);

    expect(server.tools).toEqual([
      "meta_exchange_token",
      "meta_refresh_token",
      "meta_debug_token",
      "meta_get_app_info",
      "meta_subscribe_webhook",
      "meta_get_webhook_subscriptions",
      "ig_get_capabilities",
      "ig_get_connection_info",
      "ig_bootstrap_discovery",
      "ig_publish_photo",
      "ig_publish_video",
      "ig_publish_carousel",
      "ig_publish_reel",
      "ig_publish_story",
      "ig_get_container_status",
      "ig_get_content_publishing_limit",
      "ig_get_media_list",
      "ig_get_media",
      "ig_delete_media",
      "ig_get_media_insights",
      "ig_toggle_comments",
      "ig_get_media_children",
      "ig_get_stories",
      "ig_get_live_media",
      "ig_get_comments",
      "ig_get_comment",
      "ig_post_comment",
      "ig_get_replies",
      "ig_reply_to_comment",
      "ig_hide_comment",
      "ig_delete_comment",
      "ig_send_private_reply",
      "ig_get_profile",
      "ig_get_account_insights",
      "ig_business_discovery",
      "ig_get_collaboration_invites",
      "ig_respond_collaboration_invite",
      "ig_get_collaborative_posts",
      "ig_get_business_media",
      "ig_analyze_business",
      "ig_compare_businesses",
      "ig_track_business",
      "ig_untrack_business",
      "ig_get_business_history",
      "ig_run_competitor_collection",
      "ig_competitor_research",
      "ig_search_hashtag",
      "ig_get_hashtag",
      "ig_get_hashtag_recent",
      "ig_get_hashtag_top",
      "ig_get_recently_searched_hashtags",
      "ig_get_mentioned_comment",
      "ig_get_tagged_media",
      "ig_get_mentioned_media",
      "ig_reply_to_mention",
      "ig_get_conversations",
      "ig_get_messages",
      "ig_send_message",
      "ig_get_message",
      "ig_send_media_message",
      "ig_send_quick_replies",
      "ig_send_generic_template",
      "ig_send_button_template",
      "ig_send_reaction",
      "ig_delete_reaction",
      "ig_send_sender_action",
      "ig_get_user_profile_by_igsid",
      "ig_upload_attachment",
      "ig_get_messenger_profile",
      "ig_set_ice_breakers",
      "ig_delete_ice_breakers",
      "ig_set_persistent_menu",
      "ig_delete_persistent_menu",
      "ig_list_welcome_message_flows",
      "ig_get_welcome_message_flow",
      "ig_set_welcome_message_flow",
      "ig_delete_welcome_message_flow",
      "ig_get_subscribed_apps",
      "ig_subscribe_app",
      "ig_unsubscribe_app",
      "ig_get_available_catalogs",
      "ig_get_catalog_products",
      "ig_get_product_tags",
      "ig_create_product_tags",
      "ig_delete_product_tags",
      "ig_get_product_appeal",
      "ig_submit_product_appeal",
      "ig_get_branded_content_ad_permissions",
      "ig_get_advertisable_media",
      "ig_get_authorized_ad_accounts",
      "ig_set_authorized_ad_account",
      "ig_delete_authorized_ad_account",
      "ig_get_tag_approval_requests",
      "ig_update_tag_approval",
      "ig_get_oembed",
      "threads_publish_text",
      "threads_publish_image",
      "threads_publish_video",
      "threads_publish_carousel",
      "threads_delete_post",
      "threads_get_container_status",
      "threads_get_publishing_limit",
      "threads_repost",
      "threads_search_locations",
      "threads_get_posts",
      "threads_get_post",
      "threads_search_posts",
      "threads_get_replies",
      "threads_reply",
      "threads_hide_reply",
      "threads_unhide_reply",
      "threads_get_profile",
      "threads_get_post_insights",
      "threads_get_user_insights",
      "threads_get_mentions",
    ]);

    expect(server.resources).toEqual([
      { name: "instagram-profile", uri: "meta-mcp://instagram/profile" },
      { name: "threads-profile", uri: "meta-mcp://threads/profile" },
    ]);

    expect(server.prompts).toEqual([
      "content_publish",
      "analytics_report",
    ]);
  });
});
